import type { Bank, PaymentGateway, PaymentMethod, Screenshot } from "./types";

export const SOCIAL_LINKS = {
	github: "https://github.com/mosabsomaer/Khazna",
	figma: "https://www.figma.com/community/file/1639907833706485884/khazna",
	email: "mosab.omaer@binary.ly",
};

export const BANKS: Bank[] = [
	{
		id: "sahara-bank",
		name: "Sahara Bank",
		logoUrl: "/cdn/v1/logos/banks/sahara-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/sahara-bank.svg",
		colors: ["#002C4B", "#A77B18"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "yaqeen-bank",
		name: "Yaqeen Bank",
		logoUrl: "/cdn/v1/logos/banks/yaqeen-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/yaqeen-bank.svg",
		colors: ["#0B1338", "#F47D3F"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "north-bank",
		name: "North Africa Bank",
		logoUrl: "/cdn/v1/logos/banks/north-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/north-bank.svg",
		colors: ["#0055B8", "#E87200"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "bcd-bank",
		name: "Bank of Commerce & Development",
		logoUrl: "/cdn/v1/logos/banks/bcd-bank.svg",
		logoUrlBlack: "/cdn/v1/logos/banks/bcd-bank-black.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/bcd-bank.svg",
		logomarkUrlBlack: "/cdn/v1/logos/bank-icons/bcd-bank-black.svg",
		colors: ["#007F3E", "#FFC80F"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "atib-bank",
		name: "ATIB Bank",
		logoUrl: "/cdn/v1/logos/banks/atib-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/atib-bank.svg",
		colors: ["#E30E2D"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "investment-bank",
		name: "Arab Investment Islamic Bank",
		logoUrl: "/cdn/v1/logos/banks/investment-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/investment-bank.svg",
		colors: ["#DE4148", "#E6DAC8"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "islamic-bank",
		name: "Libyan Islamic Bank",
		logoUrl: "/cdn/v1/logos/banks/islamic-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/islamic-bank.svg",
		colors: ["#735D46", "#897852"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "tadamun-bank",
		name: "Tadamun Bank",
		logoUrl: "/cdn/v1/logos/banks/tadamun-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/tadamun-bank.svg",
		colors: ["#155957", "#21B5E9", "#B5D339"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "united-bank",
		name: "United Bank",
		logoUrl: "/cdn/v1/logos/banks/united-bank.svg",
		logoUrlBlack: "/cdn/v1/logos/banks/united-bank-black.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/united-bank.svg",
		logomarkUrlBlack: "/cdn/v1/logos/bank-icons/united-bank-black.svg",
		colors: ["#304365"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "al-seraj-islamic-bank",
		name: "Al Seraj Islamic Bank",
		logoUrl: "/cdn/v1/logos/banks/al-seraj-islamic-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/al-seraj-islamic-bank.svg",
		colors: ["#6E58A5"],
		hasScreenshots: false,

		type: "bank",
	},
	{
		id: "aman-bank",
		name: "Aman Bank",
		logoUrl: "/cdn/v1/logos/banks/aman-bank.svg",
		colors: ["#102440", "#2C386B"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "andalus-bank",
		name: "Andalus Bank",
		logoUrl: "/cdn/v1/logos/banks/andalus-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/andalus-bank.svg",
		colors: ["#8C7032", "#BEA460"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "cbl-bank",
		name: "Central Bank of Libya",
		logoUrl: "/cdn/v1/logos/banks/cbl-bank.svg",
		colors: ["#211E1F"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "fglb-bank",
		name: "First Gulf Libyan Bank",
		logoUrl: "/cdn/v1/logos/banks/fglb-bank.svg",
		colors: ["#23387B", "#E62C27"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "imaar-bank",
		name: "Imaar Bank",
		logoUrl: "/cdn/v1/logos/banks/imaar-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/imaar-bank.svg",
		colors: ["#FA62FB", "#83C8FB"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "jumhouria-bank",
		name: "Jumhouria Bank",
		logoUrl: "/cdn/v1/logos/banks/jumhouria-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/jumhouria-bank.svg",
		colors: ["#002244"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "libyan-foreign-bank",
		name: "Libyan Foreign Bank",
		logoUrl: "/cdn/v1/logos/banks/libyan-foreign-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/libyan-foreign-bank.svg",
		colors: ["#051C2C"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "mediterranean-bank",
		name: "Mediterranean Bank",
		logoUrl: "/cdn/v1/logos/banks/mediterranean-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/mediterranean-bank.svg",
		colors: ["#1A61AE"],
		hasScreenshots: false,
		type: "bank",
	},
	{
		id: "national-commercial-bank",
		name: "National Commercial Bank",
		logoUrl: "/cdn/v1/logos/banks/national-commercial-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/national-commercial-bank.svg",
		colors: ["#0D4155", "#067937"],
		hasScreenshots: true,
		type: "bank",
	},
	{
		id: "nuran-bank",
		name: "Nuran Bank",
		logoUrl: "/cdn/v1/logos/banks/nuran-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/nuran-bank.svg",
		colors: ["#0093B4", "#81CCD6"],
		hasScreenshots: true,
		type: "bank",
		disableMono: true,
	},
	{
		id: "alwaha-bank",
		name: "Alwaha Bank",
		logoUrl: "/cdn/v1/logos/banks/alwaha-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/alwaha-bank.svg",
		colors: ["#FFCE6C", "#949797"],
		hasScreenshots: true,
		type: "bank",
		isUpdated: true,
	},
	{
		id: "wahda-bank",
		name: "Wahda Bank",
		logoUrl: "/cdn/v1/logos/banks/wahda-bank.svg",
		logomarkUrl: "/cdn/v1/logos/bank-icons/wahda-bank.svg",
		colors: ["#034694", "#27AAE2"],
		hasScreenshots: true,
		type: "bank",
	},
];

export const PAYMENT_METHODS: PaymentMethod[] = [
	{
		id: "sadad",
		name: "Sadad",
		logoUrl: "/cdn/v1/logos/payments/sadad.svg",
		logomarkUrl: "/cdn/v1/logos/payments/sadad-icon.svg",
		colors: ["#67696B"],
		type: "payment_method",
		disableMono: true,
	},
	{
		id: "edfa3li",
		name: "Edfa3li",
		logoUrl: "/cdn/v1/logos/payments/edfa3li.svg",
		colors: ["#0E2316", "#FEE600"],
		type: "payment_method",
		disableMono: true,
	},
	{
		id: "mobicash",
		name: "MobiCash",
		logoUrl: "/cdn/v1/logos/payments/mobicash.svg",
		logoUrlBlack: "/cdn/v1/logos/payments/mobicash-black.svg",
		colors: ["#274998", "#4AC7F0", "#F78824"],
		type: "payment_method",
		isUpdated: true,
	},
	{
		id: "masrafy-pay",
		name: "Masrafy Pay",
		logoUrl: "/cdn/v1/logos/payments/masrafy-pay.svg",
		colors: ["#1A60AB", "#39BDEE"],
		type: "payment_method",
	},
	{
		id: "ly-pay",
		name: "LY Pay",
		logoUrl: "/cdn/v1/logos/payments/ly-pay.svg",
		logomarkUrl: "/cdn/v1/logos/payments/ly-pay-icon.svg",
		colors: ["#17A3DD", "#4EB3A7"],
		type: "payment_method",
	},
	{
		id: "al-seraj-pay",
		name: "Al Seraj Pay",
		logoUrl: "/cdn/v1/logos/payments/al-seraj-pay.svg",
		colors: ["#1F1F4E", "#6C56A2"],
		type: "payment_method",
	},
	{
		id: "nab4pay",
		name: "NAB4Pay",
		logoUrl: "/cdn/v1/logos/payments/nab4pay.svg",
		colors: ["#2D84C6", "#F59F1C"],
		type: "payment_method",
	},
	{
		id: "onepay",
		name: "OnePay",
		logoUrl: "/cdn/v1/logos/payments/onepay.svg",
		colors: ["#026795", "#49C4EA"],
		type: "payment_method",
	},
	{
		id: "sahara-pay",
		name: "Sahara Pay",
		logoUrl: "/cdn/v1/logos/payments/sahara-pay.svg",
		logomarkUrl: "/cdn/v1/logos/payments/sahara-pay-icon.svg",
		colors: ["#162C49", "#AA7E1A"],
		type: "payment_method",
	},
	{
		id: "yussor-pay",
		name: "Yussor Pay",
		logoUrl: "/cdn/v1/logos/payments/yussor-pay.svg",
		colors: ["#013E50", "#057A40"],
		type: "payment_method",
	},
	{
		id: "yussor-pay-online",
		name: "Yussor Pay Online",
		logoUrl: "/cdn/v1/logos/payments/yussor-pay-online.svg",
		colors: ["#013E50", "#057A40"],
		type: "payment_method",
		isNew: true,
	},
	{
		id: "gpay",
		name: "GPay",
		logoUrl: "/cdn/v1/logos/payments/gpay.svg",
		colors: ["#0D74B8", "#010101"],
		type: "payment_method",
	},
	{
		id: "alwaha-pay",
		name: "Alwaha Pay",
		logoUrl: "/cdn/v1/logos/payments/alwaha-pay.svg",
		logomarkUrl: "/cdn/v1/logos/payments/alwaha-pay-icon.svg",
		colors: ["#FFCD65", "#909394"],
		type: "payment_method",
		isNew: true,
	},
	{
		id: "numo-pay",
		name: "Numo Pay",
		logoUrl: "/cdn/v1/logos/payments/numo-pay.svg",
		logomarkUrl: "/cdn/v1/logos/payments/numo-pay-icon.svg",
		colors: ["#404041", "#FFE000"],
		type: "payment_method",
	},
];

export const PAYMENT_GATEWAYS: PaymentGateway[] = [
	{
		id: "plutu",
		name: "Plutu",
		logoUrl: "/cdn/v1/logos/payment-gateways/plutu.svg",
		colors: ["#247872"],
		type: "payment_gateway",
		isNew: true,
	},
	{
		id: "moamalat",
		name: "Moamalat",
		logoUrl: "/cdn/v1/logos/payment-gateways/moamalat.svg",
		colors: ["#403F41", "#DFB806"],
		type: "payment_gateway",
		isNew: true,
	},
	{
		id: "t-lync",
		name: "T-Lync",
		logoUrl: "/cdn/v1/logos/payment-gateways/t-lync.svg",
		colors: ["#3E2FBB", "#00B8CE"],
		type: "payment_gateway",
		isNew: true,
	},
	{
		id: "ezone-pay",
		name: "Ezone Pay",
		logoUrl: "/cdn/v1/logos/payment-gateways/ezone-pay.svg",
		colors: ["#37B888", "#512B83"],
		type: "payment_gateway",
		isNew: true,
	},
	{
		id: "dpay",
		name: "DPay",
		logoUrl: "/cdn/v1/logos/payment-gateways/dpay.svg",
		colors: ["#00AEEF", "#1C75BC"],
		type: "payment_gateway",
		isNew: true,
	},
	{
		id: "mypay",
		name: "my pay",
		logoUrl: "/cdn/v1/logos/payment-gateways/mypay.svg",
		colors: ["#000000"],
		type: "payment_gateway",
		isNew: true,
	},
];

export const MOCK_SCREENSHOTS: Record<string, Screenshot[]> = {
	"sahara-bank": [
		{
			id: "s1",
			url: "/screenshots/sahara-bank/splash.webp",
			downloadUrl: "/screenshots/sahara-bank/splash.png",
			label: "Splash Screen",
			category: "onboarding",
		},
		{
			id: "s2",
			url: "/screenshots/sahara-bank/my-account.webp",
			downloadUrl: "/screenshots/sahara-bank/my-account.png",
			label: "My Account",
			category: "dashboard",
		},
		{
			id: "s3",
			url: "/screenshots/sahara-bank/main-menu.webp",
			downloadUrl: "/screenshots/sahara-bank/main-menu.png",
			label: "Main Menu",
			category: "dashboard",
		},
		{
			id: "s4",
			url: "/screenshots/sahara-bank/menu.webp",
			downloadUrl: "/screenshots/sahara-bank/menu.png",
			label: "Menu",
			category: "dashboard",
		},
		{
			id: "s5",
			url: "/screenshots/sahara-bank/financial-operations.webp",
			downloadUrl: "/screenshots/sahara-bank/financial-operations.png",
			label: "Financial Operations",
			category: "transaction",
		},
		{
			id: "s6",
			url: "/screenshots/sahara-bank/financial-operations-2.webp",
			downloadUrl: "/screenshots/sahara-bank/financial-operations-2.png",
			label: "Financial Operations",
			category: "transaction",
		},
		{
			id: "s7",
			url: "/screenshots/sahara-bank/account-statement.webp",
			downloadUrl: "/screenshots/sahara-bank/account-statement.png",
			label: "Account Statement",
			category: "dashboard",
		},
		{
			id: "s8",
			url: "/screenshots/sahara-bank/money-transfer.webp",
			downloadUrl: "/screenshots/sahara-bank/money-transfer.png",
			label: "Money Transfer",
			category: "transaction",
		},
		{
			id: "s9",
			url: "/screenshots/sahara-bank/qr-payment.webp",
			downloadUrl: "/screenshots/sahara-bank/qr-payment.png",
			label: "QR Payment",
			category: "transaction",
		},
		{
			id: "s10",
			url: "/screenshots/sahara-bank/qr-payment-2.webp",
			downloadUrl: "/screenshots/sahara-bank/qr-payment-2.png",
			label: "QR Payment",
			category: "transaction",
		},
		{
			id: "s11",
			url: "/screenshots/sahara-bank/qr-payment-3.webp",
			downloadUrl: "/screenshots/sahara-bank/qr-payment-3.png",
			label: "QR Payment",
			category: "transaction",
		},
		{
			id: "s12",
			url: "/screenshots/sahara-bank/buy-prepaid-cards.webp",
			downloadUrl: "/screenshots/sahara-bank/buy-prepaid-cards.png",
			label: "Buy Prepaid Cards",
			category: "transaction",
		},
		{
			id: "s13",
			url: "/screenshots/sahara-bank/prepaid-card.webp",
			downloadUrl: "/screenshots/sahara-bank/prepaid-card.png",
			label: "Prepaid Card",
			category: "dashboard",
		},
		{
			id: "s14",
			url: "/screenshots/sahara-bank/cash-withdrawal.webp",
			downloadUrl: "/screenshots/sahara-bank/cash-withdrawal.png",
			label: "Cash Withdrawal",
			category: "transaction",
		},
		{
			id: "s15",
			url: "/screenshots/sahara-bank/lypay-payment.webp",
			downloadUrl: "/screenshots/sahara-bank/lypay-payment.png",
			label: "LYPAY Payment",
			category: "transaction",
		},
		{
			id: "s16",
			url: "/screenshots/sahara-bank/lypay-payment-2.webp",
			downloadUrl: "/screenshots/sahara-bank/lypay-payment-2.png",
			label: "LYPAY Payment",
			category: "transaction",
		},
		{
			id: "s17",
			url: "/screenshots/sahara-bank/onepay-payment.webp",
			downloadUrl: "/screenshots/sahara-bank/onepay-payment.png",
			label: "OnePay Payment",
			category: "transaction",
		},
		{
			id: "s18",
			url: "/screenshots/sahara-bank/onepay-transfer.webp",
			downloadUrl: "/screenshots/sahara-bank/onepay-transfer.png",
			label: "OnePay Transfer",
			category: "transaction",
		},
		{
			id: "s19",
			url: "/screenshots/sahara-bank/financial-disclosure.webp",
			downloadUrl: "/screenshots/sahara-bank/financial-disclosure.png",
			label: "Financial Disclosure",
			category: "dashboard",
		},
		{
			id: "s20",
			url: "/screenshots/sahara-bank/transaction-password.webp",
			downloadUrl: "/screenshots/sahara-bank/transaction-password.png",
			label: "Transaction Password",
			category: "auth",
		},
	],
	"north-bank": [
		{
			id: "n1",
			url: "/screenshots/north-bank/home.webp",
			downloadUrl: "/screenshots/north-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "n2",
			url: "/screenshots/north-bank/my-account.webp",
			downloadUrl: "/screenshots/north-bank/my-account.png",
			label: "My Account",
			category: "dashboard",
		},
		{
			id: "n3",
			url: "/screenshots/north-bank/account-statement.webp",
			downloadUrl: "/screenshots/north-bank/account-statement.png",
			label: "Account Statement",
			category: "dashboard",
		},
		{
			id: "n4",
			url: "/screenshots/north-bank/cards.webp",
			downloadUrl: "/screenshots/north-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "n5",
			url: "/screenshots/north-bank/cards-2.webp",
			downloadUrl: "/screenshots/north-bank/cards-2.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "n6",
			url: "/screenshots/north-bank/cards-3.webp",
			downloadUrl: "/screenshots/north-bank/cards-3.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "n7",
			url: "/screenshots/north-bank/cards-4.webp",
			downloadUrl: "/screenshots/north-bank/cards-4.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "n8",
			url: "/screenshots/north-bank/cards-5.webp",
			downloadUrl: "/screenshots/north-bank/cards-5.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "n9",
			url: "/screenshots/north-bank/basic-services.webp",
			downloadUrl: "/screenshots/north-bank/basic-services.png",
			label: "Basic Services",
			category: "dashboard",
		},
		{
			id: "n10",
			url: "/screenshots/north-bank/card-terms.webp",
			downloadUrl: "/screenshots/north-bank/card-terms.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n11",
			url: "/screenshots/north-bank/card-terms-2.webp",
			downloadUrl: "/screenshots/north-bank/card-terms-2.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n12",
			url: "/screenshots/north-bank/card-terms-3.webp",
			downloadUrl: "/screenshots/north-bank/card-terms-3.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n13",
			url: "/screenshots/north-bank/card-terms-4.webp",
			downloadUrl: "/screenshots/north-bank/card-terms-4.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n14",
			url: "/screenshots/north-bank/card-terms-5.webp",
			downloadUrl: "/screenshots/north-bank/card-terms-5.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n15",
			url: "/screenshots/north-bank/card-terms-6.webp",
			downloadUrl: "/screenshots/north-bank/card-terms-6.png",
			label: "Card Terms",
			category: "onboarding",
		},
		{
			id: "n16",
			url: "/screenshots/north-bank/dont-count.webp",
			downloadUrl: "/screenshots/north-bank/dont-count.png",
			label: "Don't Count It",
			category: "dashboard",
		},
		{
			id: "n17",
			url: "/screenshots/north-bank/e-wallets.webp",
			downloadUrl: "/screenshots/north-bank/e-wallets.png",
			label: "Electronic Wallets",
			category: "dashboard",
		},
		{
			id: "n18",
			url: "/screenshots/north-bank/financial-obligations.webp",
			downloadUrl: "/screenshots/north-bank/financial-obligations.png",
			label: "Financial Obligations",
			category: "dashboard",
		},
		{
			id: "n19",
			url: "/screenshots/north-bank/insurance.webp",
			downloadUrl: "/screenshots/north-bank/insurance.png",
			label: "Insurance",
			category: "dashboard",
		},
		{
			id: "n20",
			url: "/screenshots/north-bank/money-transfer.webp",
			downloadUrl: "/screenshots/north-bank/money-transfer.png",
			label: "Money Transfer",
			category: "transaction",
		},
		{
			id: "n21",
			url: "/screenshots/north-bank/money-transfer-2.webp",
			downloadUrl: "/screenshots/north-bank/money-transfer-2.png",
			label: "Money Transfer",
			category: "transaction",
		},
		{
			id: "n22",
			url: "/screenshots/north-bank/payments.webp",
			downloadUrl: "/screenshots/north-bank/payments.png",
			label: "Payments",
			category: "transaction",
		},
	],
	"atib-bank": [
		{
			id: "a1",
			url: "/screenshots/atib-bank/login.webp",
			downloadUrl: "/screenshots/atib-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "a2",
			url: "/screenshots/atib-bank/date-of-birth.webp",
			downloadUrl: "/screenshots/atib-bank/date-of-birth.png",
			label: "Date of Birth",
			category: "onboarding",
		},
		{
			id: "a3",
			url: "/screenshots/atib-bank/my-account.webp",
			downloadUrl: "/screenshots/atib-bank/my-account.png",
			label: "My Account",
			category: "dashboard",
		},
		{
			id: "a4",
			url: "/screenshots/atib-bank/menu.webp",
			downloadUrl: "/screenshots/atib-bank/menu.png",
			label: "Menu",
			category: "dashboard",
		},
		{
			id: "a5",
			url: "/screenshots/atib-bank/settings.webp",
			downloadUrl: "/screenshots/atib-bank/settings.png",
			label: "Settings",
			category: "settings",
		},
		{
			id: "a6",
			url: "/screenshots/atib-bank/conversion.webp",
			downloadUrl: "/screenshots/atib-bank/conversion.png",
			label: "Conversion",
			category: "transaction",
		},
		{
			id: "a7",
			url: "/screenshots/atib-bank/buy-cards.webp",
			downloadUrl: "/screenshots/atib-bank/buy-cards.png",
			label: "Buy Cards",
			category: "transaction",
		},
	],
	"bcd-bank": [
		{
			id: "b1",
			url: "/screenshots/bcd-bank/login.webp",
			downloadUrl: "/screenshots/bcd-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "b2",
			url: "/screenshots/bcd-bank/onboarding.webp",
			downloadUrl: "/screenshots/bcd-bank/onboarding.png",
			label: "Onboarding",
			category: "onboarding",
		},
		{
			id: "b3",
			url: "/screenshots/bcd-bank/home.webp",
			downloadUrl: "/screenshots/bcd-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "b4",
			url: "/screenshots/bcd-bank/my-cards.webp",
			downloadUrl: "/screenshots/bcd-bank/my-cards.png",
			label: "My Cards",
			category: "dashboard",
		},
		{
			id: "b5",
			url: "/screenshots/bcd-bank/transfer-list.webp",
			downloadUrl: "/screenshots/bcd-bank/transfer-list.png",
			label: "Transfer List",
			category: "transaction",
		},
		{
			id: "b6",
			url: "/screenshots/bcd-bank/buy-cards.webp",
			downloadUrl: "/screenshots/bcd-bank/buy-cards.png",
			label: "Buy Cards",
			category: "transaction",
		},
		{
			id: "b7",
			url: "/screenshots/bcd-bank/branches.webp",
			downloadUrl: "/screenshots/bcd-bank/branches.png",
			label: "Branches",
			category: "dashboard",
		},
		{
			id: "b8",
			url: "/screenshots/bcd-bank/more.webp",
			downloadUrl: "/screenshots/bcd-bank/more.png",
			label: "More",
			category: "dashboard",
		},
		{
			id: "b9",
			url: "/screenshots/bcd-bank/check.webp",
			downloadUrl: "/screenshots/bcd-bank/check.png",
			label: "Check",
			category: "transaction",
		},
	],
	"andalus-bank": [
		{
			id: "and1",
			url: "/screenshots/andalus-bank/home.webp",
			downloadUrl: "/screenshots/andalus-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "and2",
			url: "/screenshots/andalus-bank/accounts.webp",
			downloadUrl: "/screenshots/andalus-bank/accounts.png",
			label: "Accounts",
			category: "dashboard",
		},
		{
			id: "and3",
			url: "/screenshots/andalus-bank/cards.webp",
			downloadUrl: "/screenshots/andalus-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "and4",
			url: "/screenshots/andalus-bank/card-store.webp",
			downloadUrl: "/screenshots/andalus-bank/card-store.png",
			label: "Card Store",
			category: "transaction",
		},
		{
			id: "and5",
			url: "/screenshots/andalus-bank/taysir-card.webp",
			downloadUrl: "/screenshots/andalus-bank/taysir-card.png",
			label: "Taysir Card",
			category: "dashboard",
		},
		{
			id: "and6",
			url: "/screenshots/andalus-bank/branches-atm.webp",
			downloadUrl: "/screenshots/andalus-bank/branches-atm.png",
			label: "Branches & ATM",
			category: "dashboard",
		},
		{
			id: "and7",
			url: "/screenshots/andalus-bank/qr.webp",
			downloadUrl: "/screenshots/andalus-bank/qr.png",
			label: "QR",
			category: "transaction",
		},
		{
			id: "and8",
			url: "/screenshots/andalus-bank/settings.webp",
			downloadUrl: "/screenshots/andalus-bank/settings.png",
			label: "Settings",
			category: "settings",
		},
		{
			id: "and9",
			url: "/screenshots/andalus-bank/ld-account.webp",
			downloadUrl: "/screenshots/andalus-bank/ld-account.png",
			label: "LYD Account",
			category: "dashboard",
		},
		{
			id: "and10",
			url: "/screenshots/andalus-bank/transfer.webp",
			downloadUrl: "/screenshots/andalus-bank/transfer.png",
			label: "Transfer",
			category: "transaction",
		},
	],
	"islamic-bank": [
		{
			id: "isl1",
			url: "/screenshots/islamic-bank/login.webp",
			downloadUrl: "/screenshots/islamic-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "isl2",
			url: "/screenshots/islamic-bank/home.webp",
			downloadUrl: "/screenshots/islamic-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "isl3",
			url: "/screenshots/islamic-bank/accounts.webp",
			downloadUrl: "/screenshots/islamic-bank/accounts.png",
			label: "Accounts",
			category: "dashboard",
		},
		{
			id: "isl4",
			url: "/screenshots/islamic-bank/cards.webp",
			downloadUrl: "/screenshots/islamic-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "isl5",
			url: "/screenshots/islamic-bank/transfer.webp",
			downloadUrl: "/screenshots/islamic-bank/transfer.png",
			label: "Transfer",
			category: "transaction",
		},
		{
			id: "isl6",
			url: "/screenshots/islamic-bank/control-panel.webp",
			downloadUrl: "/screenshots/islamic-bank/control-panel.png",
			label: "Control Panel",
			category: "settings",
		},
	],
	"nuran-bank": [
		{
			id: "nur1",
			url: "/screenshots/nuran-bank/login.webp",
			downloadUrl: "/screenshots/nuran-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "nur2",
			url: "/screenshots/nuran-bank/home.webp",
			downloadUrl: "/screenshots/nuran-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "nur3",
			url: "/screenshots/nuran-bank/account.webp",
			downloadUrl: "/screenshots/nuran-bank/account.png",
			label: "Account",
			category: "dashboard",
		},
		{
			id: "nur4",
			url: "/screenshots/nuran-bank/cards.webp",
			downloadUrl: "/screenshots/nuran-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "nur5",
			url: "/screenshots/nuran-bank/request-card.webp",
			downloadUrl: "/screenshots/nuran-bank/request-card.png",
			label: "Request Card",
			category: "transaction",
		},
		{
			id: "nur6",
			url: "/screenshots/nuran-bank/more.webp",
			downloadUrl: "/screenshots/nuran-bank/more.png",
			label: "More",
			category: "dashboard",
		},
	],
	"jumhouria-bank": [
		{
			id: "j1",
			url: "/screenshots/jumhouria-bank/login.webp",
			downloadUrl: "/screenshots/jumhouria-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "j2",
			url: "/screenshots/jumhouria-bank/visitor-area.webp",
			downloadUrl: "/screenshots/jumhouria-bank/visitor-area.png",
			label: "Visitor Area",
			category: "onboarding",
		},
		{
			id: "j3",
			url: "/screenshots/jumhouria-bank/accounts.webp",
			downloadUrl: "/screenshots/jumhouria-bank/accounts.png",
			label: "Accounts",
			category: "dashboard",
		},
		{
			id: "j4",
			url: "/screenshots/jumhouria-bank/current-account.webp",
			downloadUrl: "/screenshots/jumhouria-bank/current-account.png",
			label: "Current Account",
			category: "dashboard",
		},
		{
			id: "j5",
			url: "/screenshots/jumhouria-bank/current-account-2.webp",
			downloadUrl: "/screenshots/jumhouria-bank/current-account-2.png",
			label: "Current Account",
			category: "dashboard",
		},
		{
			id: "j6",
			url: "/screenshots/jumhouria-bank/current-account-3.webp",
			downloadUrl: "/screenshots/jumhouria-bank/current-account-3.png",
			label: "Current Account",
			category: "dashboard",
		},
		{
			id: "j7",
			url: "/screenshots/jumhouria-bank/financial-operations.webp",
			downloadUrl: "/screenshots/jumhouria-bank/financial-operations.png",
			label: "Financial Operations",
			category: "transaction",
		},
		{
			id: "j8",
			url: "/screenshots/jumhouria-bank/payment.webp",
			downloadUrl: "/screenshots/jumhouria-bank/payment.png",
			label: "Payment",
			category: "transaction",
		},
		{
			id: "j9",
			url: "/screenshots/jumhouria-bank/prepaid-cards.webp",
			downloadUrl: "/screenshots/jumhouria-bank/prepaid-cards.png",
			label: "Prepaid Cards",
			category: "dashboard",
		},
		{
			id: "j10",
			url: "/screenshots/jumhouria-bank/settings.webp",
			downloadUrl: "/screenshots/jumhouria-bank/settings.png",
			label: "Settings",
			category: "settings",
		},
		{
			id: "j11",
			url: "/screenshots/jumhouria-bank/list.webp",
			downloadUrl: "/screenshots/jumhouria-bank/list.png",
			label: "List",
			category: "dashboard",
		},
	],
	"national-commercial-bank": [
		{
			id: "ncb1",
			url: "/screenshots/national-commercial-bank/login.webp",
			downloadUrl: "/screenshots/national-commercial-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "ncb2",
			url: "/screenshots/national-commercial-bank/home.webp",
			downloadUrl: "/screenshots/national-commercial-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "ncb3",
			url: "/screenshots/national-commercial-bank/accounts.webp",
			downloadUrl: "/screenshots/national-commercial-bank/accounts.png",
			label: "My Accounts",
			category: "dashboard",
		},
		{
			id: "ncb4",
			url: "/screenshots/national-commercial-bank/accounts-2.webp",
			downloadUrl: "/screenshots/national-commercial-bank/accounts-2.png",
			label: "My Accounts",
			category: "dashboard",
		},
		{
			id: "ncb5",
			url: "/screenshots/national-commercial-bank/mailbox.webp",
			downloadUrl: "/screenshots/national-commercial-bank/mailbox.png",
			label: "Mailbox",
			category: "dashboard",
		},
		{
			id: "ncb6",
			url: "/screenshots/national-commercial-bank/mailbox-2.webp",
			downloadUrl: "/screenshots/national-commercial-bank/mailbox-2.png",
			label: "Mailbox",
			category: "dashboard",
		},
		{
			id: "ncb7",
			url: "/screenshots/national-commercial-bank/mailbox-3.webp",
			downloadUrl: "/screenshots/national-commercial-bank/mailbox-3.png",
			label: "Mailbox",
			category: "dashboard",
		},
		{
			id: "ncb8",
			url: "/screenshots/national-commercial-bank/branches-atm.webp",
			downloadUrl: "/screenshots/national-commercial-bank/branches-atm.png",
			label: "Branches & ATM",
			category: "dashboard",
		},
		{
			id: "ncb9",
			url: "/screenshots/national-commercial-bank/currency-rates.webp",
			downloadUrl: "/screenshots/national-commercial-bank/currency-rates.png",
			label: "Currency Rates",
			category: "dashboard",
		},
		{
			id: "ncb10",
			url: "/screenshots/national-commercial-bank/customer-service.webp",
			downloadUrl: "/screenshots/national-commercial-bank/customer-service.png",
			label: "Customer Service",
			category: "settings",
		},
		{
			id: "ncb11",
			url: "/screenshots/national-commercial-bank/account-opening.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb12",
			url: "/screenshots/national-commercial-bank/account-opening-2.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-2.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb13",
			url: "/screenshots/national-commercial-bank/account-opening-3.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-3.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb14",
			url: "/screenshots/national-commercial-bank/account-opening-4.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-4.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb15",
			url: "/screenshots/national-commercial-bank/account-opening-5.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-5.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb16",
			url: "/screenshots/national-commercial-bank/account-opening-6.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-6.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb17",
			url: "/screenshots/national-commercial-bank/account-opening-7.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-7.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb18",
			url: "/screenshots/national-commercial-bank/account-opening-8.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-8.png",
			label: "Account Opening",
			category: "onboarding",
		},
		{
			id: "ncb19",
			url: "/screenshots/national-commercial-bank/account-opening-9.webp",
			downloadUrl: "/screenshots/national-commercial-bank/account-opening-9.png",
			label: "Account Opening",
			category: "onboarding",
		},
	],
	"wahda-bank": [
		{
			id: "w1",
			url: "/screenshots/wahda-bank/home.webp",
			downloadUrl: "/screenshots/wahda-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "w2",
			url: "/screenshots/wahda-bank/analytics.webp",
			downloadUrl: "/screenshots/wahda-bank/analytics.png",
			label: "Analytics",
			category: "dashboard",
		},
		{
			id: "w3",
			url: "/screenshots/wahda-bank/cards.webp",
			downloadUrl: "/screenshots/wahda-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "w4",
			url: "/screenshots/wahda-bank/card-store.webp",
			downloadUrl: "/screenshots/wahda-bank/card-store.png",
			label: "Card Store",
			category: "transaction",
		},
		{
			id: "w5",
			url: "/screenshots/wahda-bank/financing-services.webp",
			downloadUrl: "/screenshots/wahda-bank/financing-services.png",
			label: "Financing Services",
			category: "dashboard",
		},
		{
			id: "w6",
			url: "/screenshots/wahda-bank/qr-payment.webp",
			downloadUrl: "/screenshots/wahda-bank/qr-payment.png",
			label: "QR Payment",
			category: "transaction",
		},
		{
			id: "w7",
			url: "/screenshots/wahda-bank/profile.webp",
			downloadUrl: "/screenshots/wahda-bank/profile.png",
			label: "Profile",
			category: "settings",
		},
		{
			id: "w8",
			url: "/screenshots/wahda-bank/verification.webp",
			downloadUrl: "/screenshots/wahda-bank/verification.png",
			label: "Verification",
			category: "auth",
		},
		{
			id: "w9",
			url: "/screenshots/wahda-bank/account-statement.webp",
			downloadUrl: "/screenshots/wahda-bank/account-statement.png",
			label: "Account Statement",
			category: "dashboard",
		},
		{
			id: "w10",
			url: "/screenshots/wahda-bank/account-statement-2.webp",
			downloadUrl: "/screenshots/wahda-bank/account-statement-2.png",
			label: "Account Statement",
			category: "dashboard",
		},
		{
			id: "w11",
			url: "/screenshots/wahda-bank/money-transfer.webp",
			downloadUrl: "/screenshots/wahda-bank/money-transfer.png",
			label: "Money Transfer",
			category: "transaction",
		},
		{
			id: "w12",
			url: "/screenshots/wahda-bank/money-transfer-2.webp",
			downloadUrl: "/screenshots/wahda-bank/money-transfer-2.png",
			label: "Money Transfer",
			category: "transaction",
		},
		{
			id: "w13",
			url: "/screenshots/wahda-bank/add-beneficiary.webp",
			downloadUrl: "/screenshots/wahda-bank/add-beneficiary.png",
			label: "Add Beneficiary",
			category: "transaction",
		},
	],
	"alwaha-bank": [
		{
			id: "aw1",
			url: "/screenshots/alwaha-bank/splash.webp",
			downloadUrl: "/screenshots/alwaha-bank/splash.png",
			label: "Splash Screen",
			category: "onboarding",
		},
		{
			id: "aw2",
			url: "/screenshots/alwaha-bank/welcome.webp",
			downloadUrl: "/screenshots/alwaha-bank/welcome.png",
			label: "Welcome",
			category: "onboarding",
		},
		{
			id: "aw3",
			url: "/screenshots/alwaha-bank/get-started.webp",
			downloadUrl: "/screenshots/alwaha-bank/get-started.png",
			label: "Get Started",
			category: "onboarding",
		},
		{
			id: "aw4",
			url: "/screenshots/alwaha-bank/login.webp",
			downloadUrl: "/screenshots/alwaha-bank/login.png",
			label: "Login",
			category: "auth",
		},
		{
			id: "aw5",
			url: "/screenshots/alwaha-bank/home.webp",
			downloadUrl: "/screenshots/alwaha-bank/home.png",
			label: "Home",
			category: "dashboard",
		},
		{
			id: "aw6",
			url: "/screenshots/alwaha-bank/side-menu.webp",
			downloadUrl: "/screenshots/alwaha-bank/side-menu.png",
			label: "Menu",
			category: "dashboard",
		},
		{
			id: "aw7",
			url: "/screenshots/alwaha-bank/services.webp",
			downloadUrl: "/screenshots/alwaha-bank/services.png",
			label: "Services",
			category: "dashboard",
		},
		{
			id: "aw8",
			url: "/screenshots/alwaha-bank/select-recipient.webp",
			downloadUrl: "/screenshots/alwaha-bank/select-recipient.png",
			label: "Select Recipient",
			category: "transaction",
		},
		{
			id: "aw9",
			url: "/screenshots/alwaha-bank/transfer-amount.webp",
			downloadUrl: "/screenshots/alwaha-bank/transfer-amount.png",
			label: "Transfer Amount",
			category: "transaction",
		},
		{
			id: "aw10",
			url: "/screenshots/alwaha-bank/transfer-confirmation.webp",
			downloadUrl: "/screenshots/alwaha-bank/transfer-confirmation.png",
			label: "Transfer Confirmation",
			category: "transaction",
		},
		{
			id: "aw11",
			url: "/screenshots/alwaha-bank/verification-code.webp",
			downloadUrl: "/screenshots/alwaha-bank/verification-code.png",
			label: "Verification",
			category: "auth",
		},
		{
			id: "aw12",
			url: "/screenshots/alwaha-bank/transfer-processing.webp",
			downloadUrl: "/screenshots/alwaha-bank/transfer-processing.png",
			label: "Transfer Processing",
			category: "transaction",
		},
		{
			id: "aw13",
			url: "/screenshots/alwaha-bank/transfer-success.webp",
			downloadUrl: "/screenshots/alwaha-bank/transfer-success.png",
			label: "Transfer Success",
			category: "transaction",
		},
		{
			id: "aw14",
			url: "/screenshots/alwaha-bank/transfer-receipt.webp",
			downloadUrl: "/screenshots/alwaha-bank/transfer-receipt.png",
			label: "Transfer Receipt",
			category: "transaction",
		},
		{
			id: "aw15",
			url: "/screenshots/alwaha-bank/buy-prepaid-cards.webp",
			downloadUrl: "/screenshots/alwaha-bank/buy-prepaid-cards.png",
			label: "Buy Prepaid Cards",
			category: "transaction",
		},
		{
			id: "aw16",
			url: "/screenshots/alwaha-bank/my-cards.webp",
			downloadUrl: "/screenshots/alwaha-bank/my-cards.png",
			label: "My Cards",
			category: "transaction",
		},
		{
			id: "aw17",
			url: "/screenshots/alwaha-bank/cards.webp",
			downloadUrl: "/screenshots/alwaha-bank/cards.png",
			label: "Cards",
			category: "dashboard",
		},
		{
			id: "aw18",
			url: "/screenshots/alwaha-bank/card-details.webp",
			downloadUrl: "/screenshots/alwaha-bank/card-details.png",
			label: "Card Details",
			category: "dashboard",
		},
		{
			id: "aw19",
			url: "/screenshots/alwaha-bank/statement-request.webp",
			downloadUrl: "/screenshots/alwaha-bank/statement-request.png",
			label: "Statement Request",
			category: "dashboard",
		},
		{
			id: "aw20",
			url: "/screenshots/alwaha-bank/account-statement.webp",
			downloadUrl: "/screenshots/alwaha-bank/account-statement.png",
			label: "Account Statement",
			category: "dashboard",
		},
		{
			id: "aw21",
			url: "/screenshots/alwaha-bank/settings.webp",
			downloadUrl: "/screenshots/alwaha-bank/settings.png",
			label: "Settings",
			category: "settings",
		},
	],
};
